name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Ensure this matches the setup-node version

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} # Use matrix version
        cache: 'npm'
        cache-dependency-path: package-lock.json # Updated path

    - name: Install Dependencies
      run: npm ci

    - name: Run Lint
      run: npm run lint 

    - name: Build Project
      run: npm run build --if-present

    - name: Run Tests
      run: npm test
